### PR TITLE
added saveNRRD() to Sweep.jl

### PR DESCRIPTION
**Pull request by anchal-physics**
Added function saveNRRD(filename,sj::SweepJob)
This function saves the SweepJob data in NRRD format.
Following is breif decription of the format it would save in. For more details, see http://teem.sourceforge.net/nrrd/
The data will be saved in form of two files:
1) .nhdr (Header File)
This file is metadata and helps NRRD readers to read the file.
2) .txt (Data File)
This file will have data in it. If the data is real, it is simply a single column of all elements of sweep.result in order specified by Sizes: field in the header file.
If the data is complex, it is same as above but with two columns, first being real value of the element and second being imaginary part.

Example:
Data is as follow with job_id 2717
3-dimensional AxisArray{Complex{Float64},3,...} with axes:
    :sparam, Symbol[:S11, :S21]
    :f, [5.5e9, 5.5005e9, 5.501e9]
    :ramp, -0.25:0.005:-0.235
And data, a 2×3×4 Array{Complex{Float64},3}:
[:, :, 1] =
 -0.0182041-0.0078326im  -0.0103763-0.00229047im  -0.0183401-0.00772569im
   0.536571-0.683058im     0.420013-0.700748im      0.316085-0.76124im

[:, :, 2] =
 -0.0184039-0.0073684im  -0.0154158-0.00700348im  -0.0137233-0.00150677im
   0.540023-0.554489im     0.386438-0.666069im      0.353078-0.68932im

[:, :, 3] =
 -0.0110112-0.00650227im  -0.018174-0.00591373im  -0.015121-0.0114015im
   0.554959-0.626im        0.422671-0.662709im     0.394596-0.75237im

[:, :, 4] =
 -0.011287-0.0115502im  -0.0208357-0.00888762im  -0.0146494-0.010862im
  0.550647-0.602843im     0.454867-0.774955im      0.281862-0.722243im

Then Header file will be:
NRRD0004
Content: Job ID 2717
Type: double
Dimension: 4
Encoding: ascii
Endian: little
Sizes: 2 2 3 4
Kind: complex 2-vector domain domainr
Labels: Complex sparam_S11_S21 Frequency Ramp
Datafile: 2717.txt

With Data file being:
-0.0182040584731	-0.00783260388899
0.53657107576	-0.683057891721
-0.0103762556157	-0.00229047154763
0.420012957679	-0.700748283174
-0.0183400709829	-0.00772569422832
0.316085495213	-0.761239689493
-0.0184039405165	-0.0073683971052
0.540023425999	-0.554489358869
-0.0154158368275	-0.00700347836966
0.386438420296	-0.666068566732
-0.0137233113896	-0.00150676546548
0.353077532683	-0.689319516149
-0.0110112011269	-0.00650227291971
0.554959011833	-0.62599972143
-0.0181739889084	-0.00591372891842
0.42267124645	-0.662709067628
-0.0151209658728	-0.0114014624835
0.394596212939	-0.75237043158
-0.0112870070071	-0.0115501912538
0.550646587879	-0.602843388083
-0.0208356947057	-0.00888761767796
0.454867267869	-0.774955448349
-0.0146494243437	-0.0108620493525
0.281861821623	-0.722242617874

### CODE REVIEW

**Comment by ajkeller34** [comment]
Thanks, will check this out. Don't merge yet but I'm going to add you to the repository.

**Comment by ajkeller34** [comment]
Looks like a good initial effort and glad to see you trying to use the pull requests. I have several comments:

- Have you checked to see if NRRD is a useful file format for us, in the sense that it accomplishes the goal of being easily imported into Matlab, Mathematica, or others? In the meeting notes I suggested you take a look at it, but I don't know if it is or if it isn't. I also mentioned MAT.jl in the meeting notes, which would enable data to be easily imported into Matlab if nothing else.

- Provided you think there is good reason to go with NRRD, you appear to be duplicating a lot of functionality from the package NRRD.jl, also mentioned in our meeting notes. You should use that package instead. It has already been tested by the Julia community (and has test code to make sure it continues to work), so you don't have to worry about maintaining it because someone else is doing it already. Then, together with the FileIO package, provided you have an AxisArray with real values it should be as easy as `save("/path/to/file.nrrd", myaxisarray)`.

  Of course, sometimes we have complex AxisArrays, and you mentioned NRRD doesn't expect complex numbers. I would resurrect the code from the e-mail I sent you and just write a function that turns a complex AxisArray into a real AxisArray with an additional axis to represent the real/imag parts. If you have determined that the NRRD format suffices for our needs, that could very well be the extent of this pull request.

- You've committed directly to the master branch of your fork of InstrumentControl.jl. A better strategy is to make a different branch (even if it's your own fork), commit to that, and then open the pull request. I may not have mentioned that in our git tutorial, but otherwise, it's awkward to try and work on separate independent PRs simultaneously, and you may run into trouble with the original repo's master branch getting out of sync with your fork's master branch. I'd probably give you the wrong instructions if I explained how to fix this situation here so we should sit down and do this together.

**Comment by anchal-physics** [comment]
Hi Andrew,

- There are NRRD readers available for both Matlab and Python (I guess 2 mostly used languages in our lab) and the multidimensionality function of NRRD format convinced me that it is probably the best pre-existing format we could use. I accept though that I didn't look around much apart from NRRD.
- I looked into NRRD.jl package and gave some time in understanding it. I was getting errors when I tried to simply use save function with AxisArrays. I also thought it would be a better idea to be able to use NRRD.jl but the effort I was putting into doing it seemed like too much for our purpose in comparison to me writing a simple code that does our job. Specifically, because NRRD is a very general format, so I felt maybe NRRD.jl is for all purposes while we can use the definitions of format to work out our purpose.
- However, if you insist that we should try out a way to be able to use NRRD.jl, I can try more to make it work for us.
- Regarding committing to master branch of my fork, frankly, I didn't understand well the reasoning you gave me so let's meet to work this out. I would like to learn to do this the proper way.

**Comment by ajkeller34** [comment]
Yes, I think you should just use NRRD.jl. My guess is that you just needed to do `using FileIO` in addition to `using NRRD`, otherwise there shouldn't be any errors. Another advantage of that package (provided that the Matlab and Python readers work well) is that NRRD.jl saves the data in binary rather than plain text, which saves a lot of disk space for large arrays.

I'll come find you this afternoon to discuss git branches.

**Comment by ajkeller34** [comment]
Per our discussion earlier, I found the following in the NRRD manual, somewhere in [here](http://teem.sourceforge.net/nrrd/lib.html):

> Because nrrd has the mentality that "everything is a scalar", you'll need a 4-D array to represent a volume in which each voxel has multiple values associated with it, such as with a 3-D vector field. The "kind" per-axis information is how nrrd provides guidance on representing this situation:
> ```
> nrrdAxisInfoSet(nvec, nrrdAxisInfoKind,
>                 nrrdKind3Vector, nrrdKindSpace, nrrdKindSpace, nrrdKindSpace);
> nrrdAxisInfoSet(nvec, nrrdAxisInfoLabel, "Vx;Vy;Vz", "x", "y", "z");
> ```

In the case of symbols along an axis, I guess the "list" kind from the table at the end of [this page](http://teem.sourceforge.net/nrrd/format.html) would be appropriate, since the number of symbols is unknown. It looks like you used "2-vector" which works for our typical VNA data set but maybe not in general. You had the right idea with the labels though: the labels can be used to describe the different "components" of the data.

Seems like we should do the following:

- Fork NRRD.jl, make a new branch
- Add support for "categorical axes," and some tests to make sure it works properly.
- Submit PR.
- Profit.

This could be somewhat complicated but it's the best way to go because then everyone can make use of your efforts, the code is tested, and you can say you contributed to a widely used package. So let's find time to sit down together. Plus you'll get some practice with git. Maybe we can start between the software meeting and 4pm tomorrow? I think we'll need to edit the code somewhere around [here](https://github.com/JuliaIO/NRRD.jl/blob/5dc8058e5062a26d0e0c127440316f3b39e07f44/src/NRRD.jl#L396).

Two helpful points:

- If I just run Julia from the command line I get the full stack trace for the error you saw when you were saving. I'm not sure why you don't see it in the Jupyter notebook.
- You can use backticks (`) to quote code on Github and have it formatted nicely. Triple backticks will quote an entire multi-line block of code. You can use the "preview" tab when you write a comment to see how it works.

**Comment by anchal-physics** [comment]
I think you are right on using "list" kind for the dependent axis. I used 2-vector in the example but the code was able to deal up to 4-dimensional data (I thought all S-parameters might be the maximum we calculate). Anyways, making it "list" is the best way to generalize code for all dimensional dependent axis.
I'll try some preliminary things before we meet today.

**Comment by vtdsferreira** [comment]
Whatever happened to this, did we put it on hold? Should we close this pull request and come back to this saving issue once the code is more stable and not changing so much?

**Comment by anchal-physics** [comment]
I was supposed to fork out NRRD.jl and make it such that it can be used for our purposes. But as this wasn't that urgent, I've put a pause on it for now. You can close this pull request I guess.

**Pull request closed without merging**
